package com.pydrud.pydash;

/**
 * Compile-time runtime configuration, generated by {@code pydrud sync}.
 *
 * Do not edit by hand: change {@code pydrud.yaml} (or run
 * {@code pydrud init android --backend …}) and re-sync.
 */
public final class PydrudRuntimeConfig {

    private PydrudRuntimeConfig() {
    }

    /** The selected backend: {@code "chaquopy"}, {@code "host"} or
     *  {@code "none"}. */
    public static final String BACKEND = "chaquopy";

    /** Host backend: the machine running {@code pydrud dev}. */
    public static final String REMOTE_HOST = "127.0.0.1";

    /** Host backend: the bridge port the host listens on. */
    public static final int REMOTE_PORT = 8597;
}
