"""Backward-compatible imports for reusable Pydash components.

New code should import from :mod:`app.components`. This module remains so apps
generated by earlier Pydrud versions can move files gradually.
"""

from app.components import (
    brand_hero, card, meta_list, notice_state, section_header, stat_tile,
    status_dot, status_pill, step_row,
)

__all__ = [
    "brand_hero", "card", "meta_list", "notice_state", "section_header",
    "stat_tile", "status_dot", "status_pill", "step_row",
]
